### ISSUE TITLE
Maintainers list is badly formed

### ISSUE THREAD

**Issue by pelson** [conda-forge/pandoc-feedstock#1]
Hi @JanSchulz. Just wanted to let you know that the maintainers list is causing a little issue at https://github.com/conda-forge/conda-forge.github.io/issues/40. This is simply because:

```
extra:
  recipe-maintainers:
    -janschulz
```

rather than

```
extra:
  recipe-maintainers:
    - janschulz
```

(notice the space)

I'll update the conda-forge scripts to be less fragile, but it would also be handy if you would be able to update the feedstock with the fix too. We should also update the smithy linter to double check the formatting.

Thanks!

**Comment by JanSchulz** [comment]
Also fixed in the pandoc-feedstock

**Comment by pelson** [comment]
Thanks @JanSchulz
