### ISSUE TITLE
appveyor is failing

### ISSUE THREAD

**Issue by ickc** [conda-forge/pandoc-feedstock#110]
Currently, continuous-integration/appveyor/branch is failing with the message

> The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.

The failing started in the following PRs:

- https://github.com/conda-forge/pandoc-feedstock/pull/57
- https://github.com/conda-forge/pandoc-feedstock/pull/58

where @ocefpaf commented in https://github.com/conda-forge/pandoc-feedstock/pull/57#issuecomment-501279850 that he downgraded conda-build at the moment to clear the error in #57.

Any idea how to fix this? Thanks!

**Comment by ocefpaf** [comment]
My comment here is not related to AppVeyor and you can ignore that failure.

**Comment by ickc** [comment]
It is now passing as shown in #109, thanks to @beckermr from gitter.

**Comment by ickc** [comment]
@ocefpaf, it is not a good practice to close an issue before it is resolved. Please leave them open until it is resolved, even if it might not be related to the comment you made.

(It is resolved however by a separate effort so it is not reopening.)

**Comment by ocefpaf** [comment]
> @ocefpaf, it is not a good practice to close an issue before it is resolved. Please leave them open until it is resolved, even if it might not be related to the comment you made.

Is was resolved already when I closed. That IS why I closed. Bad practice is to self-merge reverts like in #108 ;-p

**Comment by ickc** [comment]
@ocefpaf, you have not mentioned why it is closing, that's why I assumed it is because of your answer.

Did you know why it was now passing? Were you aware of the activities in gitter? Even if so, you should mention that in this issue before closing.

Are you done with your drama? This repo is failing for years and I volunteer my free time to fix this. Is it how you are treating fellow volunteers?

**Comment by ickc** [comment]
@ocefpaf, let's be frank, during the last 2.5 years, this error has been persistent in all the PRs, including many that you have merged.

This few days I started to ask around and see why this is failing. This issue is opened for the first time in 2.5 years to track this. Someone else helped and resolved this. And you think you have the right to close this without giving any explanation, just because the error disappears.

And should I even believe you that you know it is resolved when you close? It was still failing at the latest master branch. It was only started passing in one of the PR I created.

And what kind of comment is that in #108? Did you follow through the referenced PRs before you speak?

Do you feel so entitled that just because you're maintainer joined earlier, other maintainer should be asking you for opinion for something as simple as #108 (again explained in the referenced PR for reason that should not be controversial at all.) Or are you just picking fight trying to find something to argue?

Now I give you the chance to either apologize or prove yourself right—if you can call for a vote and the other maintainers of this feedstock agrees with you, I will shut up and remove myself as a maintainer. If not, may be you should do that instead.

Stop wasting other people's time if you don't care about maintaining properly here.

**Comment by ocefpaf** [comment]
Let's be Frank, it was non issue. Please reconsider your attitude and stop self merging complex decisions.

**Comment by ocefpaf** [comment]
BTW, your attitude can be considered a violation of our code of conduct. I'm asking you to stop now. If you continue I'll be force to act.

1. Appveyor hook was removed a few times and returned, as @beckermr mention to you.
2. It wasn't an issue and never prevent a PKG from being built.
3. You attacked me b/c I asked you to not self merge a complex PR that reverted the change of a core member.
4. Your are being aggressive and without respect for co-maintainers.

**Comment by beckermr** [comment]
I am going to lock this issue for now. Let's all take a breather and reflect on how we treat others.
