### ISSUE TITLE
create pandoc-crossref feedstock

### ISSUE THREAD

**Issue by kiwi0fruit** [conda-forge/pandoc-feedstock#27]
There is a nice [pandoc-crossref](https://github.com/lierdakil/pandoc-crossref) filter. And it has [releases](https://github.com/lierdakil/pandoc-crossref/releases) in the same manner as Pandoc has.

So I guess this feedstock can be adapted to new pandoc-crossref feedstock...

**Comment by ocefpaf** [comment]
@kiwi0fruit it would mean a new package. For that one would need to send a PR to [staged-recipes](https://github.com/conda-forge/staged-recipes/blob/master/README.md) to create the new feedstock.

Do you want to try it?

(Closing this b/c it is not an actionable issue for the team of this feedstock.)

**Comment by kiwi0fruit** [comment]
@ocefpaf I guess it's a good starting point... After all I need to make recipies for *panflute* and *pandoctools*. By adapting I meant usung the script from here at staged-recipes.

**Comment by ocefpaf** [comment]
Ping me on your PR to staged-recipes if you need anu help.

**Comment by gandalfsaxe** [comment]
Hoping to see this :)
