### ISSUE TITLE
Wrong install place

### ISSUE THREAD

**Issue by kiwi0fruit** [conda-forge/pandoc-feedstock#28]
Pandoc on Windows installs to `\Scripts` folder. But the right place for large binaries seems to be `\Library\bin`.

**Comment by ocefpaf** [comment]
I guess that scripts is "OK" b/c it is also on the PATH, but I agree that lib/bin seems to be more appropriated. Do you want to try to send a PR to fix that?

**Comment by janschulz** [comment]
The script sflder is put into PATH when activating a conda environment. I'm currently unsure if that also happens with any other directory. This makes it suitable to use that dir to make that pandoc available for the jupyter notebook to convert notebooks to latex (together with miktex, which also places binaries in that folder). If you move it away, this usecase should still work afterwards...

**Comment by kiwi0fruit** [comment]
@janschulz On Windows `\Library\bin` is added to `PATH` on `activate` (or on install in case of root env - if you select default options). I guess `lib/bin` is also added to `PATH` on Unix on `activate`.

**Comment by kiwi0fruit** [comment]
@ocefpaf Not yet. I want to create some other recipes first (6 recipes actually).

**Comment by kiwi0fruit** [comment]
@jankatins This use case (Jupyter and co) always happen with conda activate env or can be without it (may be Jupyter works great without activation...)?

**Comment by jankatins** [comment]
If the default installer puts it there, then IMO everything which would take it out is your own problem (on the other hand, anacondas own kernel manager for envs does not activate an env, but I'm not anymore sure if that would mean Script would be in the search path when calling  `pandoc` from within a python interpreter) ...

You should then probably go through the miktex package as well..

**Comment by kiwi0fruit** [comment]
This bug-like thing is actual on Windows only (I've finally checked how Miniconda on Linux befaves).

**Comment by kiwi0fruit** [comment]
But who cares...
