### ISSUE TITLE
Build from source?

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/pandoc-feedstock#54]
We have the haskell build tools.  this should be feasible

**Comment by rolweber** [comment]
This could resolve a dependency conflict on ppc64le between pandoc and recent builds of Python.
https://github.com/ContinuumIO/anaconda-issues/issues/11887

**Comment by louy2** [comment]
Can this also potentially provide osx-arm64 build? It is already available on Homebrew: https://github.com/jgm/pandoc/issues/6960#issuecomment-861368945

**Comment by anjos** [comment]
Is there any technical show stoppers for this to be implemented?  Otherwise, I can probably do a bit on this.

Any tips are appreciated/welcome (for example, pointers to other conda-forge haskell packages).

**Comment by anjos** [comment]
After a bit of investigation, pandoc requires `cabal` to compile or cross-compile.  That tool, in turn, is not available on all platforms via conda-forge yet, which makes it difficult to advance on this issue (see state here https://github.com/conda-forge/cabal-feedstock).  There is also some discussion going on about ghc packaging itself (https://github.com/conda-forge/ghc-feedstock/pull/24).  We need to wait for those things to settle before touching here.

**Comment by ickc** [comment]
I’m not sure that’s true, you can use stack to compile pandoc if that’s what you mean.

**Comment by anjos** [comment]
You are right, it was an oversight from my part.  Are there examples of other software projects in conda-forge using stack to build?

**Comment by ickc** [comment]
Probably this is: https://github.com/conda-forge/git-annex-feedstock
It may be the only one according to https://cs.github.com/?scope=org%3Aconda-forge&scopeName=conda-forge&q=haskell+AND+stack+AND+%28path%3A*.yml+OR+path%3A*.yaml%29

**Comment by anjos** [comment]
Thank you, @ickc.  This looks more challenging that I expected -- that example includes ghc bootstrapping, as it seems.  I naively thought you could just have `stack` on the build requirements, or `ghc`, and after that, a simple `stack build/install` or `ghc pandoc...` would work.

**Comment by jakirkham** [comment]
cc @xhochy (as the discussion above may be of interest)

**Comment by mfansler** [comment]
Are there any status updates on this? I've been postponing requesting an `r-rmarkdown` **osx-arm64** migration because I know this is an essential dependency.

**Comment by anjos** [comment]
For info, the homebrew recipe, for which this package has an installable pre-compiled bottle uses cabal and ghc to build it (https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pandoc.rb).  The build instructions seem rather straightforward and copy-able from a naive perspective.  However, cabal is not available for osx-arm64 (or osx for that matter, c.f. https://github.com/conda-forge/cabal-feedstock).  The "cabal" feedstock seems unmaintained.

Also, it seems cabal is being deprecated in favour of stack (https://docs.haskellstack.org/en/stable/README/).  However our recipe for it (https://github.com/conda-forge/stack-feedstock) also does not support osx-arm64.  So, we are a bit stuck.  To start, one would have to probably fix that first.

**Comment by ickc** [comment]
It is equally simple to use stack too. See pandoc documentation.
