### ISSUE TITLE
Pandoc Abort trap 6.

### ISSUE THREAD

**Issue by Carreau** [conda-forge/pandoc-feedstock#67]
Pandoc failed to convert GFM markdown with fence code block w/ python language marker. 

    $ \cat ex.md
    If I remove python in the fence below, it works

    ```python
    def f():
       pass
    ```

```
$ pandoc -f gfm -t latex ex.md
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/bussonniermatthias/miniconda3/bin/pandoc
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /Users/bussonniermatthias/miniconda3/bin/pandoc
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

That's regardless of the language I convert to.

**Comment by Carreau** [comment]
to be clearer. 

    ```python
     ...
    ```

fails

    ```
     ...
    ```
works.

**Comment by ocefpaf** [comment]
Our pandoc is repackaged from the official release, this is probably a problem upstream.

**Comment by Carreau** [comment]
Ok, thanks. Closing then.

**Comment by ocefpaf** [comment]
> Ok, thanks. Closing then.

Could you confirm that it was the upstream installer? I don't have a macOS to check :-(
