### ISSUE TITLE
Pandoc 2.13 is missing for linux64

### ISSUE THREAD

**Issue by m-rossi** [conda-forge/pandoc-feedstock#89]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Pandoc 2.13 is missing for linux64: https://anaconda.org/conda-forge/pandoc/files?version=2.13
Looking at the CI, the build process for linux64 failed. Can some maintainer restart the CI or should I open a PR with increased `number`?

**Comment by ocefpaf** [comment]
Just restart the CIs in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=317328&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97 fingers crossed!

**Comment by ocefpaf** [comment]
Should be up now. Thanks for the report!

**Comment by m-rossi** [comment]
Looks good, thanks! :-)
